version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db-app
    env_file:
      - .env-non-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    build:
      context: .
    container_name: ylab_fastApi_app
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      - db