
version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db-app
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=${POSTGRES_SERVER}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylab_fastApi_app_with_tests
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started

  pytest:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: tests
    env_file:
      - .env
    environment:
      - HOST_FOR_TEST=${HOST_FOR_TEST}
    depends_on:
      app:
        condition: service_started