version: "3.7"

services:
version: "3.7"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db-app
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 3s
      timeout: 30s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ylab_fastApi_app_with_tests
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  pytest:
    build:
      context: .
      dockerfile: Dockerfile-tests
    container_name: tests
    depends_on:
      app:
        condition: service_started